# Generated by Django 5.2.6 on 2025-09-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAR_INVENTORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=15)),
                ('year_of_manufacture', models.IntegerField()),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=15)),
                ('mileage', models.IntegerField()),
                ('number_of_seats', models.IntegerField()),
            ],
        ),
    ]
